### ISSUE TITLE
Add xs variant to typography and button

### ISSUE THREAD

**Issue by TangoYankee** [NYCPlanning/ae-streetscape#65]
## Acceptance criteria
- [ ] Add an xs variant to Typography with value `0.75rem`
- [ ] Add an xs variant to Button

**Comment by jessicashanshanhuang** [comment]
Hey @TangoYankee!

The only feedback I have is when I minimize my screen to test the responsiveness, the timeline portion becomes pretty big compared to the other elements. 



![Convert to GIF project Aug 08](https://github.com/user-attachments/assets/79a5f58c-e526-4fcc-a5cb-1e954b77e234)

**Comment by TangoYankee** [comment]
Good catch! I [responded on the implementation ticket](https://github.com/NYCPlanning/ae-cp-map/issues/17#issuecomment-2276215361) for the timeline (trying to keep the conversation centralized)
